[mypy]
python_version = 3.9
warn_unused_ignores = True
warn_redundant_casts = True
show_error_codes = True
check_untyped_defs = True

[mypy-src.mddocx.converter.elements.*]
disallow_untyped_defs = False

[mypy-markdown_it.*]
ignore_missing_imports = True

[mypy-mdit_py_plugins.*]
ignore_missing_imports = True

[mypy-docx.*]
ignore_missing_imports = True

[mypy-html4docx.*]
ignore_missing_imports = True

[mypy-bs4.*]
ignore_missing_imports = True

[mypy-bleach.*]
ignore_missing_imports = True

[mypy-flask.*]
ignore_missing_imports = True

[mypy-flask_wtf.*]
ignore_missing_imports = True

[mypy-werkzeug.*]
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True
