#!/usr/bin/env bash
# Universal Super Cursor layout check
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CUR="$ROOT/.cursor"
FAIL=0

check() { [[ -e "$1" ]] && echo "OK  $1" || { echo "FAIL $1"; FAIL=$((FAIL+1)); }; }
check_absent() { [[ -e "$1" ]] && { echo "FAIL must not exist: $1"; FAIL=$((FAIL+1)); } || echo "OK  absent $1"; }
check_grep_absent() {
  local dir="$1" pattern="$2"
  if grep -rq --exclude="verify-super-cursor.sh" "$pattern" "$dir" 2>/dev/null; then
    echo "FAIL $dir contains $pattern"
    FAIL=$((FAIL+1))
  else
    echo "OK  no '$pattern' in $(basename "$dir") tree"
  fi
}

echo "=== Super Cursor verify (universal) ==="
check "$CUR/rules/core.mdc"
check "$CUR/rules/workflow.mdc"
check "$CUR/rules/feedback/changelog.mdc"
check "$CUR/rules/feedback/verify.mdc"
check "$CUR/rules/execution/submodule.mdc"
check "$CUR/config/workflow.json"
check "$CUR/config/release.json"
check "$CUR/config/README.md"
check "$CUR/templates/plan.md"
if [[ -f "$CUR/templates/plan.md" ]] && ! grep -qE '^\*\*(执行顺序|Order)\*\*' "$CUR/templates/plan.md" 2>/dev/null; then
  echo "FAIL templates/plan.md missing **执行顺序** line"
  FAIL=$((FAIL+1))
else
  echo "OK  templates/plan.md has execution order line"
fi
check "$CUR/rules/communication/collaboration.mdc"
check "$CUR/rules/execution/docs.mdc"
check "$CUR/rules/execution/commit.mdc"
check "$CUR/rules/execution/bugfix.mdc"
check "$CUR/templates/cursorGrowth/README.md"
check "$CUR/templates/cursorGrowth/learn/plan-conventions.md"
check "$CUR/hooks/growth-init.sh"
check "$CUR/hooks/run-start.sh"
check "$CUR/hooks/run-stop.sh"
check "$CUR/hooks/lib/config-load.sh"
check "$CUR/hooks/lib/plan-parse.sh"
check "$CUR/hooks/lib/json-utils.sh"
check "$CUR/README.md"   # .cursor/README.md
check "$CUR/verify-system.sh"
check "$CUR/lib/platform.sh"
check "$CUR/skills/master/SKILL.md"
check "$CUR/skills/master/routes.md"
check "$CUR/bin/runner-smoke.sh"
check "$CUR/bin/bootstrap-growth.sh"
check "$CUR/bin/install-smoke.sh"
check "$ROOT/install-super-cursor.sh"
check "$CUR/config/profiles/full.json"
check "$CUR/config/profiles/lite.json"
check "$CUR/config/profiles/rules-only.json"
check "$CUR/docs/walkthrough.md"
check "$CUR/rules/tech/rust.mdc"
check "$CUR/rules/tech/nextjs.mdc"
check "$CUR/skills/plan/SKILL.md"
check "$CUR/skills/run/SKILL.md"
check "$CUR/skills/learn/SKILL.md"
check "$CUR/skills/scaffold/SKILL.md"
check "$CUR/skills/git/SKILL.md"
check "$CUR/skills/release/SKILL.md"
check "$CUR/commands/plan.md"
check "$CUR/commands/run.md"
check "$CUR/commands/master.md"
check "$CUR/commands/learn.md"
check "$CUR/commands/scaffold.md"
check "$CUR/commands/release.md"
check "$CUR/skills/delivery/SKILL.md"
check "$CUR/skills/ux/SKILL.md"
check "$CUR/skills/ia/SKILL.md"
check "$CUR/commands/ux.md"
check "$CUR/commands/ia.md"
check "$CUR/commands/delivery.md"
check "$CUR/skills/security/SKILL.md"
check "$CUR/skills/api/SKILL.md"
check "$CUR/rules/tech/c.mdc"
check "$CUR/rules/communication/constitution.mdc"
check "$CUR/rules/feedback/evolution.mdc"
check "$CUR/rules/execution/cli-python.mdc"
check "$CUR/rules/execution/vibe.mdc"
check "$CUR/rules/execution/scope.mdc"
check "$CUR/rules/execution/testing.mdc"
check "$CUR/rules/communication/agent-discipline.mdc"
check "$CUR/config/roles.json"
check "$CUR/skills/debug/SKILL.md"
check "$CUR/skills/test/SKILL.md"
check "$CUR/skills/mcp/SKILL.md"
check "$CUR/skills/refactor/SKILL.md"
check "$CUR/skills/perf/SKILL.md"
check "$CUR/rules/tech/eslint.mdc"
check "$CUR/rules/tech/javascript.mdc"
check "$CUR/rules/execution/security-sdlc.mdc"
check "$CUR/skills/review/SKILL.md"
check "$CUR/skills/study/SKILL.md"
check "$CUR/agents/review.md"
check "$CUR/agents/spike.md"
check "$CUR/docs/migration-catalog.md"
check "$CUR/bin/scaffold.sh"
check "$CUR/bin/scaffold-integrity.sh"
check "$CUR/templates/scaffold/manifest.json"
check "$CUR/docs/training/skills.md"
check "$CUR/docs/quickstart.md"
check "$CUR/docs/platforms.md"
check "$ROOT/.cursorignore"
check "$CUR/templates/scaffold/_shared.cursorignore"
check "$CUR/bin/template-verify.sh"
check_absent "$ROOT/scripts"
check_absent "$ROOT/examples"
check "$ROOT/.github/workflows/verify.yml"
check "$CUR/skills/release/SKILL.md"
check "$CUR/agents/ship.md"
check "$CUR/AGENTS.md"
check "$CUR/docs/naming.md"
check "$CUR/docs/rules-catalog.md"
check "$CUR/bin/runner.sh"
check "$CUR/bin/platform-check.sh"
check "$CUR/hooks.json"
check "$CUR/bin/cursor-coherence.sh"
check "$CUR/bin/validate-commit-msg.sh"
check "$CUR/rules/tech/cpp.mdc"
check "$CUR/rules/tech/typescript.mdc"
check "$CUR/rules/tech/react.mdc"
check "$CUR/rules/tech/vue.mdc"
check "$CUR/rules/tech/svelte.mdc"
check "$CUR/rules/tech/go.mdc"
check "$CUR/rules/tech/java.mdc"
check "$CUR/rules/tech/python.mdc"
check "$CUR/rules/execution/api.mdc"
check "$CUR/rules/execution/ux.mdc"
check "$CUR/rules/execution/ia.mdc"
check "$CUR/rules/execution/delivery.mdc"
check "$CUR/rules/execution/async-progress.mdc"
check "$CUR/rules/execution/long-running-ui.mdc"
check "$CUR/rules/execution/modal-layering.mdc"
check "$CUR/rules/execution/error-context.mdc"
check "$CUR/rules/execution/single-detector.mdc"
check "$CUR/rules/execution/data-batch.mdc"
check "$CUR/rules/feedback/release.mdc"
check "$CUR/rules/feedback/tag.mdc"
check_absent "$ROOT/domain-packages"
check_absent "$ROOT/profiles"
check_absent "$CUR/agents/release.md"
check_absent "$CUR/rules/index.mdc"
check_absent "$CUR/rules/feedback/growth.mdc"
check_grep_absent "$CUR" "date -Iseconds"

check_grep_absent "$CUR" "master 指令"


echo "--- platform helpers ---"
# shellcheck source=lib/platform.sh
source "$CUR/lib/platform.sh"
ts="$(iso8601_now)"
[[ -n "$ts" ]] && echo "OK  iso8601_now=$ts" || { echo "FAIL iso8601_now"; FAIL=$((FAIL+1)); }
pf="$(json_cfg "$CUR/config/workflow.json" plan_file __missing__)"
[[ "$pf" == ".cursorGrowth/plan.md" ]] && echo "OK  json_cfg plan_file=$pf" || { echo "FAIL json_cfg plan_file=$pf"; FAIL=$((FAIL+1)); }
we="$(json_cfg "$CUR/config/workflow.json" workflow.enabled __missing__)"
[[ "$we" == "true" ]] && echo "OK  json_cfg workflow.enabled=$we" || { echo "FAIL json_cfg workflow.enabled=$we"; FAIL=$((FAIL+1)); }

echo "---"
[[ "$FAIL" -eq 0 ]] && echo "All checks passed." && exit 0
echo "$FAIL check(s) failed." && exit 1
